alert("touch the screen to start");
const lyrics = [
  "You're absolutely stunning",
  "You're breathtaking",
  "You're radiant",
  "You're divine",
  "You're so mesmerizing",
  "You're so dazzling",
  "You're gorgeous beyond words",
  "You light up the room",
  "You're a vision of beauty",
  "You're perfection in form",
  "You're absolutely gorgeous",
  "You're a true beauty",
  "You're glowing",
  "You’re a natural wonder",
  "Your beauty is overwhelming",
  "You are breathtakingly beautiful",
  "You make everything shine",
  "You're a masterpiece",
  "You're absolutely captivating",
  "Your smile is radiant",
  "You're so graceful",
  "You're an angel on Earth",
  "You're an inspiration",
  "You're mesmerizing",
  "Your presence is stunning",
  "Your beauty takes my breath away",
  "You're a sight to behold",
  "Your elegance is unmatched",
  "You exude beauty",
  "You’re a true gem",
  "You're a rare beauty",
  "You're stunningly gorgeous",
  "You're flawless",
  "Your charm is irresistible",
  "You're an epitome of grace",
  "Your beauty is out of this world",
  "You're a dream come true",
  "You're pure perfection",
  "You have an enchanting beauty",
  "Your beauty radiates from within",
  "You're exquisite",
  "You're so enchanting",
  "You're an absolute vision",
  "Your beauty is captivating",
  "You radiate elegance",
  "You're the definition of beauty",
  "You're a work of art",
  "You're stunning in every way",
  "You're perfect just as you are",
  "You're the epitome of elegance",
  "Your eyes are mesmerizing",
  "You’re undeniably beautiful",
  "You shine brighter than the stars",
  "Your beauty is beyond compare",
  "You have a captivating presence",
  "You're a true vision of loveliness",
  "You're an absolute stunner",
  "Your natural beauty is breathtaking",
  "You're a perfect blend of beauty and grace",
  "You are gorgeous inside and out",
  "Your beauty leaves me speechless",
  "You're the most beautiful person I know",
  "You're stunning beyond words",
  "You're perfectly radiant",
  "You're as beautiful as a sunset",
  "You have the most beautiful soul",
  "You're an embodiment of elegance",
  "You glow like the moon",
  "You're a true beauty in every sense",
  "You're a treasure",
  "Your beauty is like no other",
  "You’re effortlessly beautiful",
  "You're more than beautiful",
  "You're unbelievably gorgeous",
  "You make the world a more beautiful place",
  "You light up the world with your beauty",
  "You're a walking miracle",
  "Your beauty shines from the inside out",
  "You're a flawless beauty",
  "You are perfection personified",
  "You're a real-life goddess",
  "You're beyond beautiful",
  "Your beauty is magical",
  "You're stunning, inside and out",
  "Your beauty is like a dream",
  "You're a vision of grace",
  "You’re a natural beauty",
  "You are the picture of beauty",
  "You are a rare masterpiece",
  "You're the most beautiful thing I've ever seen",
  "You're pure beauty",
  "You're an extraordinary beauty",
  "You're a beauty that radiates",
  "You're graceful beyond words",
  "You’re a true beauty in every sense of the word",
  "Your beauty is breathtakingly real",
  "You are the epitome of beauty",
  "You are the embodiment of grace",
  "You're as beautiful as a sunrise",
  "You’re beyond compare",
  "You're incredibly beautiful",
  "You’re a treasure of beauty",
  "You're more than just beautiful",
  "You're a beauty to behold",
  "You are a vision of perfection",
  "You're the most stunning person",
  "Your beauty shines brighter than gold",
  "You are a radiant beauty",
  "You’re the picture of elegance",
  "You're truly a masterpiece",
  "Your beauty is radiant and pure",
  "You're an angel of beauty",
  "You're effortlessly stunning",
  "You're magnificently beautiful",
  "Your presence is enchanting",
  "You're a beauty to remember",
  "Your beauty is simply mesmerizing",
  "You're a star in the sky",
  "You’re mesmerizingly beautiful",
  "You're out of this world beautiful",
  "You’re a natural wonder",
  "You're the epitome of grace",
  "You're naturally stunning",
  "You’re a timeless beauty",
  "You leave me speechless with your beauty",
  "You're a goddess of beauty",
  "You're stunning from every angle",
  "Your beauty is unforgettable",
  "You have a timeless beauty",
  "You're beyond stunning",
  "You are as beautiful as the stars",
  "You're like a work of art",
  "You're magnificent",
  "You're a timeless classic",
  "You are radiant beyond belief",
  "You are beauty personified",
  "You're the most gorgeous person I’ve seen",
  "You have an ethereal beauty",
  "You're impossibly beautiful",
  "You shine brighter than anything else",
  "You're the definition of elegance",
  "You exude natural beauty",
  "Your beauty is truly rare",
  "You're a breathtaking sight",
  "You make my heart skip a beat",
  "You're the most beautiful soul",
  "You light up the room with your beauty",
  "Your beauty is so captivating",
  "You're like a dream come true",
  "You’re divine in every way",
  "You are pure elegance",
  "You're a living work of art",
  "You're a vision in every sense",
  "Your beauty transcends everything",
  "You're a one-in-a-million beauty",
  "Your beauty is a masterpiece",
  "You leave everyone in awe with your beauty",
  "You're so radiantly beautiful",
  "You make the world more beautiful",
  "You're truly an angel",
  "You're a living angel",
  "You're perfection incarnate",
  "You're a miracle of beauty",
  "You're an enchanting beauty",
  "You're the purest form of beauty",
  "You shine like no other",
  "You're the personification of beauty",
  "Your beauty is legendary",
  "You're my vision of beauty",
  "You're the most beautiful person in the world",
  "Your beauty is awe-inspiring",
  "You have an unearthly beauty",
  "You have a beauty that makes hearts race",
  "You're a vision of loveliness",
  "Your smile is enough to brighten anyone's day",
  "You're a true jewel",
  "You're a beacon of beauty",
  "Your beauty is a rare treasure",
  "You're a dazzling jewel",
  "You're a radiant star",
  "Your beauty is out of this world",
  "You're an absolute beauty",
  "You’re more than just beautiful, you’re extraordinary",
  "You’re my forever beauty",
  "Your beauty is truly magical",
  "You're the most beautiful star in the sky",
  "You're a timeless treasure",
  "You're more stunning than words can describe",
  "You're a beauty that never fades",
  "You're a star that lights up my life",
  "Your beauty is a gift to the world",
  "You're an eternal beauty",
  "You're a beauty that will last forever",
  "You're my shining star",
  "You’re the perfect picture of beauty",
  "You’re more than beautiful, you’re breathtaking",
  "You're pure elegance",
  "You're simply a marvel",
  "You are a gem",
  "You're the queen of beauty",
  "You're a goddess of elegance",
  "You're absolutely flawless",
  "You have a beauty that can’t be matched",
  "Your beauty radiates from your soul",
  "You're the most beautiful thing in my life",
  "You’re a true queen of beauty",
  "You're my most precious beauty",
  "You're more than beautiful, you’re extraordinary",
  "You're the light of my life",
  "You're simply stunning",
  "You're the definition of beauty",
  "You're more beautiful than a thousand sunsets",
  "You're my most beautiful angel",
  "You are the queen of hearts",
  "You make the world more beautiful",
  "You're the most radiant woman",
  "You're a true work of art",
  "You are beyond beautiful",
  "You're the most precious jewel",
  "You are radiant like the sun",
  "You’re the epitome of everything beautiful",
  "You are a living masterpiece",
  "You're the crown jewel of beauty",
  "You’re the epitome of grace and elegance",
  "Your beauty is my favorite thing in the world",
  "You're the definition of elegance and beauty",
  "You're a precious diamond",
  "You shine brighter than all the stars combined",
  "You are an incredible work of art",
  "Your beauty is outshone only by your soul",
  "You are stunning in every way imaginable",
  "You are more beautiful than a rose in bloom",
  "Your beauty is unmatched",
  "You take my breath away with your beauty",
  "You're truly unforgettable",
  "You are a true masterpiece of beauty",
  "You’re breathtaking beyond words",
  "You are more than stunning",
  "You are a dream come true",
  "You are an angel sent from above",
  "You shine brighter than the stars"
];

const lyricsElement = document.getElementById("lyrics");
const song = document.getElementById("song");
let index = 0;
let songStarted = false;

function updateLyrics() {
  if (songStarted) {
    lyricsElement.innerText = lyrics[index];
    index = (index + 1) % lyrics.length;
  }
}

function startMusic() {
  if (!songStarted) {
    song.src = "./music/Sofine.mp3";
    song.muted = false;
    song.play().then(() => {
      song.loop = true;
      songStarted = true;
      setInterval(updateLyrics, 2000);
      updateLyrics();
    }).catch(error => console.log("Autoplay blocked:", error));
  }
}

document.addEventListener("click", startMusic);
document.addEventListener("touchstart", startMusic);
document.addEventListener("keypress", startMusic);

window.onload = function() {
  setTimeout(startMusic, 1000);
};